name: Rust-CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Build --no-default-features
        run: cargo build --verbose --no-default-features
      - name: Build --all-features
        run: cargo build --verbose --all-features --all-targets
      - name: Run tests
        run: cargo test --verbose
      - name: Run tests --all-features
        run: cargo test --verbose --all-features
